"""Stage 1 — download the BodyParts3D parts used by CardioTwin.

Downloads every STL referenced in ``anatomy/config/anatomy.json`` (plus the parts list and
licence text) into ``anatomy/raw/`` (git-ignored), skipping files that are already present
and intact, then writes ``anatomy/SOURCES.md`` with the provenance of every file
(ID, English name, size, SHA-256 and the required licence credit).

Usage::

    ./.venv/Scripts/python anatomy/scripts/fetch_bodyparts3d.py [--force] [--jobs 8]
"""
from __future__ import annotations

import argparse
import hashlib
import struct
import sys
import time
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import ANATOMY_DIR, RAW_DIR, all_part_ids, load_config, node_specs  # noqa: E402

SOURCES_MD = ANATOMY_DIR / "SOURCES.md"
USER_AGENT = "CardioTwin-anatomy-pipeline/1.0"


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def stl_is_intact(path: Path) -> bool:
    """A binary STL is intact when its size matches the triangle count in its header."""
    if not path.exists() or path.stat().st_size < 84:
        return False
    with open(path, "rb") as fh:
        head = fh.read(84)
    if head[:5].lower() == b"solid" and b"\n" in head:  # ASCII STL: accept if non-empty
        return path.stat().st_size > 100
    (n_tri,) = struct.unpack("<I", head[80:84])
    return path.stat().st_size == 84 + 50 * n_tri


def stl_triangle_count(path: Path) -> int:
    with open(path, "rb") as fh:
        head = fh.read(84)
    return struct.unpack("<I", head[80:84])[0]


def download(url: str, dest: Path, retries: int = 4) -> None:
    tmp = dest.with_suffix(dest.suffix + ".part")
    last_err: Exception | None = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
            with urllib.request.urlopen(req, timeout=120) as resp, open(tmp, "wb") as out:
                while chunk := resp.read(1 << 20):
                    out.write(chunk)
            tmp.replace(dest)
            return
        except (urllib.error.URLError, TimeoutError, ConnectionError) as err:
            last_err = err
            time.sleep(2.0 * (attempt + 1))
    raise RuntimeError(f"failed to download {url}: {last_err}")


def parse_parts_list(path: Path) -> dict[str, str]:
    names: dict[str, str] = {}
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            cols = line.rstrip("\n").split("\t")
            if len(cols) >= 2:
                names[cols[0].strip('"')] = cols[1].strip()
    return names


def write_sources(cfg: dict, names: dict[str, str]) -> None:
    src = cfg["source"]
    used_by: dict[str, list[str]] = {}
    for spec in node_specs(cfg):
        for pid in spec.parts:
            used_by.setdefault(pid, []).append(spec.node)
    lines = [
        "# Anatomical sources",
        "",
        "All meshes are taken from **BodyParts3D** (Database Center for Life Science, Japan) through the",
        f"GitHub mirror `{src['base_url']}`.",
        "",
        f"> {src['credits']}.",
        f"> Licence: [{src['license']}]({src['license_url']}). The derived GLB "
        "(`frontend/public/anatomy/cardiotwin_anatomy.glb`) is a modified work and is redistributed under the same licence.",
        "",
        "This file is generated by `anatomy/scripts/fetch_bodyparts3d.py`; SHA-256 digests identify the exact",
        "input files the committed assets were built from.",
        "",
        "| ID | BodyParts3D name | Used in node | Triangles | Bytes | SHA-256 |",
        "| --- | --- | --- | ---: | ---: | --- |",
    ]
    for pid in all_part_ids(cfg):
        path = RAW_DIR / f"{pid}.stl"
        lines.append(
            f"| `{pid}` | {names.get(pid, '?')} | {', '.join(f'`{n}`' for n in used_by[pid])} "
            f"| {stl_triangle_count(path):,} | {path.stat().st_size:,} | `{sha256_of(path)}` |"
        )
    SOURCES_MD.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--force", action="store_true", help="re-download even if the file is present")
    ap.add_argument("--jobs", type=int, default=8, help="parallel downloads")
    args = ap.parse_args(argv)

    cfg = load_config()
    src = cfg["source"]
    RAW_DIR.mkdir(parents=True, exist_ok=True)

    jobs: list[tuple[str, Path]] = []
    for meta in src["metadata_files"]:
        dest = RAW_DIR / meta
        if args.force or not dest.exists() or dest.stat().st_size == 0:
            jobs.append((f"{src['base_url']}/{meta}", dest))
    for pid in all_part_ids(cfg):
        dest = RAW_DIR / f"{pid}.stl"
        if args.force or not stl_is_intact(dest):
            jobs.append((f"{src['base_url']}/{src['stl_path'].format(id=pid)}", dest))

    print(f"[fetch] {len(all_part_ids(cfg))} parts referenced, {len(jobs)} file(s) to download")
    with ThreadPoolExecutor(max_workers=max(1, args.jobs)) as pool:
        futures = {pool.submit(download, url, dest): dest for url, dest in jobs}
        for fut in as_completed(futures):
            fut.result()
            print(f"[fetch]   ok {futures[fut].name} ({futures[fut].stat().st_size:,} B)")

    bad = [pid for pid in all_part_ids(cfg) if not stl_is_intact(RAW_DIR / f"{pid}.stl")]
    if bad:
        print(f"[fetch] ERROR: corrupt or missing STL(s): {bad}", file=sys.stderr)
        return 1

    names = parse_parts_list(RAW_DIR / "parts_list_e.txt")
    missing_names = [pid for pid in all_part_ids(cfg) if pid not in names]
    if missing_names:
        print(f"[fetch] ERROR: IDs not found in parts_list_e.txt: {missing_names}", file=sys.stderr)
        return 1
    write_sources(cfg, names)
    print(f"[fetch] wrote {SOURCES_MD.relative_to(ANATOMY_DIR.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
